var GAME_LEVELS = [
  ["                                           ",
   "                                           ",
   "                                           ",
   "                                           ",
   "                                           ",
   "xx  @                                      ",
   " xxxxxxxxxx xxxxx xxxx xxxx xxxxx xxxx     ",
   "       x      x   x  x x  x   x      x     ",
   "       xxxx   x   xxxx xxx    x      x     ",
   "          x   x   x  x x  x   x      x     ",
   "       xxxx   x   x  x x  x   x      x     ",
   "                                     x     ",
   "                                     x     ",
   "                                     x  o  ",
   "                                     xttttt",
   "                                           ",
   "                                           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                           "],






  ["x          xxxxxxxxxxxxxxxxxxxxxx              xxxxxxxxxxx",
   "x          xxxxxxxxxxxxxxxxxxxxxx      o       xxxxxxxxxxx",
   "x          xxxxxx        xx    xx      t                  ",
   "x          xxxxxx o         xx                            ",
   "x          xxxxxxtt    xxxxxxxxxxxxxfffffffxxxxx          ",
   "x          x          xxxxxxxxxxxxxxfffffffxxxxx=         ",
   "x          x         xxxxxxxxxxxxxxxfffffffxxxxxo       =o",
   "x          xo      xxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxx   xxxx",
   "x          xt                                       o     ",
   "x  @  o    x                                              ",
   "xxxxxxxx   x   tttt                                       ",
   "           x                                        o     ",
   "           x          tttt                        x   x   ",
   "           x                                      x   x   ",
   " o       xxx                 tttt                 x   x   ",
   "        xxxx                    x                 xo  x   ",
   "xxx    xxxxx                    x                 xt  x   ",
   "x                  o   o   o    xxxxxxx x         x   x   ",
   "x                                 o  o  x         x  ox   ",
   "x             xxxx   x   x   xxxxxxxxxxxx         x  tx   ",
   "xx           xxxxx   x   x   xxxxxxxxxxxx         x   x   ",
   "xxx         xxxxxx   x   x   xxxxxxxxxxxx         x   x   ",
   "xxxxxxxxxxxxxxxxxx   x   x   xxxxxxxxxxxx         x   x   ",
   "                                                          "],


  ["x   xxxxfffffffffffffffffffffxx xxxx xxxxx        x   ",
   "x   xxxxfffffffffffffffffffffxx xxxx xxxxx            ",
   "x   xxxxfffffffffffffffffffffxxoxxxxoxxxxx o          ",
   "x   xxxxfffffffffffffffffffffxx xxxx xxxxx        x   ",
   "x   xxxxxxxxxvxxxxvxxxxvxxxxxxx xxxx xxxxxttttt   x   ",
   "x   xxxxo                                x        x   ",
   "x   xxxxxx                   xxxxxxxxxxx x=      tx   ",
   "x   xxxxx                   xxxxxxxxxxxxox        x o ",
   "x   xxxx   xxxxxxxxxxxxxxxxxxxffffffffxx x        x   ",
   "x         xxxxxxxxxx             v     x x     tttx o ",
   "x@ o     xxxxxxxxxxx                    oxo       x   ",
   "xxxxxxxxxxx  o o  xx                     x       =x   ",
   "xxxxxxxxxxx o o o                        xttt     x   ",
   "x            o o  xxtttt                 x        x o ",
   "x xxxxxxxxxxxxxxxxxx              xxxxxxxx=       x   ",
   "     |                     tttt   x            tttx   ",
   "                                  x               x   ",
   " o                                x      ttt      x   ",
   "xxx                                               x   ",
   "xxxx                              x            tttx   ",
   "xxxxx                   xxxxxxxxxxx=              x   ",
   "xxxxxx                 xxxxxxxxxxxx               x   ",
   "xxxxxxxxxx   xxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                      "],


  ["                                                        ",
   "                  xxxxxxxxx   xxxxxxx   xxxxxxx   xxxxxx",
   "                          xxxxx o o xxxxx o o xxxxx     ",
   "                   =                             =      ",
   "                                  b      =           o  ",
   "      =    b                =                  =       =",
   "                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                  xx r r r r r r r r r r r r r r r r    ",
   "               t                                        ",
   "                                                        ",
   "           t             b           b                  ",
   "                                                   b    ",
   "            tttt              t            b            ",
   "                   x o o x        t                     ",
   "                   xxxxxxx       b    t                 ",
   "          b                                x o x        ",
   "                     b       b             xxxxx        ",
   "         =                              b           =   ",
   "            ttttt   o   ttttt   o   ttttt               ",
   "                          =                             ",
   "     xxxx          ttt         ttt                      ",
   " @   xxxx                                               ",
   "xxxxxxxxx                                               ",
   "                                                        "],


  ["                                           ",
   "                                           ",
   "                                           ",
   "                                           ",
   "                                           ",
   "    @  o o o    o o      o          o o o  ",
   "xxxxxxxxxxxxx  xxxxx    xxx        xxxxxxxx",
   "     x           x      x  x       x       ",
   "     x           x      x   xx     x       ",
   "     xxx         x      x    xx    x       ",
   "     x           x      x     xx   x       ",
   "     x           x      x       x  x       ",
   "     x         xxxxx    x        xxx       ",
   "                                           ",
   "                                           ",
   "                                           ",
   "                                           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                           "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
